/* CVS $Id: $ */
package at.ac.univie.mminf.oai2lod.vocab; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:doc/modsv3.n3 
 * @author Auto-generated by schemagen on 01 Nov 2008 10:48 
 */
public class MODS {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.RDFS_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.mediaspaces.info/schemes/mods/v3#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final OntProperty abstract_ = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#abstract" );
    
    public static final OntProperty alternativeTitle = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#alternativeTitle" );
    
    public static final OntProperty corporateName = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#corporateName" );
    
    public static final OntProperty ddcClassification = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#ddcClassification" );
    
    public static final OntProperty geographic = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#geographic" );
    
    public static final OntProperty lccClassification = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#lccClassification" );
    
    public static final OntProperty note = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#note" );
    
    public static final OntProperty personalName = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#personalName" );
    
    public static final OntProperty subTitle = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#subTitle" );
    
    public static final OntProperty title = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#title" );
    
    public static final OntProperty topic = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#topic" );
    
    public static final OntProperty urlLocation = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/mods/v3#urlLocation" );
    
}
