/* CVS $Id: $ */
package at.ac.univie.mminf.oai2lod.vocab; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:doc/oai-pmh.n3 
 * @author Auto-generated by schemagen on 01 Nov 2008 10:45 
 */
public class OAI {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    public static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.RDFS_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.mediaspaces.info/vocab/oai-pmh.rdf#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Links to the origin of an OAI-PMH Item or Set harvested by the OAI2LOD Server.</p> */
    public static final OntProperty origin = m_model.createOntProperty( "http://www.mediaspaces.info/vocab/oai-pmh.rdf#origin" );
    
    /** <p>The set an item belongs to.</p> */
    public static final OntProperty set = m_model.createOntProperty( "http://www.mediaspaces.info/vocab/oai-pmh.rdf#set" );
    
    /** <p>Holds community-specific descriptions about the set.</p> */
    public static final OntProperty setDescription = m_model.createOntProperty( "http://www.mediaspaces.info/vocab/oai-pmh.rdf#setDescription" );
    
    /** <p>A short human-readable string naming the set.</p> */
    public static final OntProperty setName = m_model.createOntProperty( "http://www.mediaspaces.info/vocab/oai-pmh.rdf#setName" );
    
    /** <p>A unique identifier for the set within the repository.</p> */
    public static final OntProperty setSpec = m_model.createOntProperty( "http://www.mediaspaces.info/vocab/oai-pmh.rdf#setSpec" );
    
    /** <p>A constituent of a repository from which metadata about a resource can be 
     *  disseminated.</p>
     */
    public static final OntClass Item = m_model.createClass( "http://www.mediaspaces.info/vocab/oai-pmh.rdf#Item" );
    
    /** <p>A set is an optional construct for grouping items for the purpose of selective 
     *  harvesting</p>
     */
    public static final OntClass Set = m_model.createClass( "http://www.mediaspaces.info/vocab/oai-pmh.rdf#Set" );
    
}
