/* CVS $Id: $ */
package at.ac.univie.mminf.oai2lod.vocab; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:doc/onb_schema.n3 
 * @author Auto-generated by schemagen on 04 Nov 2008 14:35 
 */
public class ONB {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.RDFS_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.mediaspaces.info/schemes/onb#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final OntProperty authorfirstname = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#authorfirstname" );
    
    public static final OntProperty authorlastname = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#authorlastname" );
    
    public static final OntProperty classification = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#classification" );
    
    public static final OntProperty contributor = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#contributor" );
    
    public static final OntProperty date = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#date" );
    
    public static final OntProperty info = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#info" );
    
    public static final OntProperty mimeType = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#mimeType" );
    
    public static final OntProperty origin = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#origin" );
    
    public static final OntProperty publisher = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#publisher" );
    
    public static final OntProperty rights = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#rights" );
    
    public static final OntProperty title = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#title" );
    
    public static final OntProperty topic = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#topic" );
    
    public static final OntProperty url = m_model.createOntProperty( "http://www.mediaspaces.info/schemes/onb#url" );
    
    public static final OntClass Image = m_model.createClass( "http://www.mediaspaces.info/schemes/onb#Image" );
    
}
